/* soapH.h
   Generated by gSOAP 2.8.19 from all.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_byte(soap, data),0) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_int(soap, data),0) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, const double *, const char*, const char*);

#ifndef soap_write_double
#define soap_write_double(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_double(soap, data),0) || soap_put_double(soap, data, "double", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);

#ifndef soap_read_double
#define soap_read_double(soap, data) ( soap_begin_recv(soap) || !soap_get_double(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, enum xsd__boolean *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const enum xsd__boolean *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_xsd__boolean2s(struct soap*, enum xsd__boolean);
SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, enum xsd__boolean *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2xsd__boolean(struct soap*, const char*, enum xsd__boolean *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, const enum xsd__boolean *, const char*, const char*);

#ifndef soap_write_xsd__boolean
#define soap_write_xsd__boolean(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_xsd__boolean(soap, data),0) || soap_put_xsd__boolean(soap, data, "xsd:boolean", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, enum xsd__boolean *, const char*, const char*);

#ifndef soap_read_xsd__boolean
#define soap_read_xsd__boolean(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__boolean(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (80)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data),0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (79)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data),0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data),0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data),0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE___tempuri__Test_
#define SOAP_TYPE___tempuri__Test_ (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___tempuri__Test_(struct soap*, struct __tempuri__Test_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___tempuri__Test_(struct soap*, const struct __tempuri__Test_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___tempuri__Test_(struct soap*, const char*, int, const struct __tempuri__Test_ *, const char*);
SOAP_FMAC3 struct __tempuri__Test_ * SOAP_FMAC4 soap_in___tempuri__Test_(struct soap*, const char*, struct __tempuri__Test_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___tempuri__Test_(struct soap*, const struct __tempuri__Test_ *, const char*, const char*);

#ifndef soap_write___tempuri__Test_
#define soap_write___tempuri__Test_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___tempuri__Test_(soap, data),0) || soap_put___tempuri__Test_(soap, data, "-tempuri:Test", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __tempuri__Test_ * SOAP_FMAC4 soap_get___tempuri__Test_(struct soap*, struct __tempuri__Test_ *, const char*, const char*);

#ifndef soap_read___tempuri__Test_
#define soap_read___tempuri__Test_(soap, data) ( soap_begin_recv(soap) || !soap_get___tempuri__Test_(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE___tempuri__GetCardBuyList_
#define SOAP_TYPE___tempuri__GetCardBuyList_ (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___tempuri__GetCardBuyList_(struct soap*, struct __tempuri__GetCardBuyList_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___tempuri__GetCardBuyList_(struct soap*, const struct __tempuri__GetCardBuyList_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___tempuri__GetCardBuyList_(struct soap*, const char*, int, const struct __tempuri__GetCardBuyList_ *, const char*);
SOAP_FMAC3 struct __tempuri__GetCardBuyList_ * SOAP_FMAC4 soap_in___tempuri__GetCardBuyList_(struct soap*, const char*, struct __tempuri__GetCardBuyList_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___tempuri__GetCardBuyList_(struct soap*, const struct __tempuri__GetCardBuyList_ *, const char*, const char*);

#ifndef soap_write___tempuri__GetCardBuyList_
#define soap_write___tempuri__GetCardBuyList_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___tempuri__GetCardBuyList_(soap, data),0) || soap_put___tempuri__GetCardBuyList_(soap, data, "-tempuri:GetCardBuyList", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __tempuri__GetCardBuyList_ * SOAP_FMAC4 soap_get___tempuri__GetCardBuyList_(struct soap*, struct __tempuri__GetCardBuyList_ *, const char*, const char*);

#ifndef soap_read___tempuri__GetCardBuyList_
#define soap_read___tempuri__GetCardBuyList_(soap, data) ( soap_begin_recv(soap) || !soap_get___tempuri__GetCardBuyList_(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE___tempuri__UpdateMemberInfo_
#define SOAP_TYPE___tempuri__UpdateMemberInfo_ (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___tempuri__UpdateMemberInfo_(struct soap*, struct __tempuri__UpdateMemberInfo_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___tempuri__UpdateMemberInfo_(struct soap*, const struct __tempuri__UpdateMemberInfo_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___tempuri__UpdateMemberInfo_(struct soap*, const char*, int, const struct __tempuri__UpdateMemberInfo_ *, const char*);
SOAP_FMAC3 struct __tempuri__UpdateMemberInfo_ * SOAP_FMAC4 soap_in___tempuri__UpdateMemberInfo_(struct soap*, const char*, struct __tempuri__UpdateMemberInfo_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___tempuri__UpdateMemberInfo_(struct soap*, const struct __tempuri__UpdateMemberInfo_ *, const char*, const char*);

#ifndef soap_write___tempuri__UpdateMemberInfo_
#define soap_write___tempuri__UpdateMemberInfo_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___tempuri__UpdateMemberInfo_(soap, data),0) || soap_put___tempuri__UpdateMemberInfo_(soap, data, "-tempuri:UpdateMemberInfo", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __tempuri__UpdateMemberInfo_ * SOAP_FMAC4 soap_get___tempuri__UpdateMemberInfo_(struct soap*, struct __tempuri__UpdateMemberInfo_ *, const char*, const char*);

#ifndef soap_read___tempuri__UpdateMemberInfo_
#define soap_read___tempuri__UpdateMemberInfo_(soap, data) ( soap_begin_recv(soap) || !soap_get___tempuri__UpdateMemberInfo_(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE___tempuri__VipRegisterInfo_
#define SOAP_TYPE___tempuri__VipRegisterInfo_ (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___tempuri__VipRegisterInfo_(struct soap*, struct __tempuri__VipRegisterInfo_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___tempuri__VipRegisterInfo_(struct soap*, const struct __tempuri__VipRegisterInfo_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___tempuri__VipRegisterInfo_(struct soap*, const char*, int, const struct __tempuri__VipRegisterInfo_ *, const char*);
SOAP_FMAC3 struct __tempuri__VipRegisterInfo_ * SOAP_FMAC4 soap_in___tempuri__VipRegisterInfo_(struct soap*, const char*, struct __tempuri__VipRegisterInfo_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___tempuri__VipRegisterInfo_(struct soap*, const struct __tempuri__VipRegisterInfo_ *, const char*, const char*);

#ifndef soap_write___tempuri__VipRegisterInfo_
#define soap_write___tempuri__VipRegisterInfo_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___tempuri__VipRegisterInfo_(soap, data),0) || soap_put___tempuri__VipRegisterInfo_(soap, data, "-tempuri:VipRegisterInfo", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __tempuri__VipRegisterInfo_ * SOAP_FMAC4 soap_get___tempuri__VipRegisterInfo_(struct soap*, struct __tempuri__VipRegisterInfo_ *, const char*, const char*);

#ifndef soap_read___tempuri__VipRegisterInfo_
#define soap_read___tempuri__VipRegisterInfo_(soap, data) ( soap_begin_recv(soap) || !soap_get___tempuri__VipRegisterInfo_(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE___tempuri__UpdateVipCent_
#define SOAP_TYPE___tempuri__UpdateVipCent_ (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___tempuri__UpdateVipCent_(struct soap*, struct __tempuri__UpdateVipCent_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___tempuri__UpdateVipCent_(struct soap*, const struct __tempuri__UpdateVipCent_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___tempuri__UpdateVipCent_(struct soap*, const char*, int, const struct __tempuri__UpdateVipCent_ *, const char*);
SOAP_FMAC3 struct __tempuri__UpdateVipCent_ * SOAP_FMAC4 soap_in___tempuri__UpdateVipCent_(struct soap*, const char*, struct __tempuri__UpdateVipCent_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___tempuri__UpdateVipCent_(struct soap*, const struct __tempuri__UpdateVipCent_ *, const char*, const char*);

#ifndef soap_write___tempuri__UpdateVipCent_
#define soap_write___tempuri__UpdateVipCent_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___tempuri__UpdateVipCent_(soap, data),0) || soap_put___tempuri__UpdateVipCent_(soap, data, "-tempuri:UpdateVipCent", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __tempuri__UpdateVipCent_ * SOAP_FMAC4 soap_get___tempuri__UpdateVipCent_(struct soap*, struct __tempuri__UpdateVipCent_ *, const char*, const char*);

#ifndef soap_read___tempuri__UpdateVipCent_
#define soap_read___tempuri__UpdateVipCent_(soap, data) ( soap_begin_recv(soap) || !soap_get___tempuri__UpdateVipCent_(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE___tempuri__GetVipCard2_
#define SOAP_TYPE___tempuri__GetVipCard2_ (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___tempuri__GetVipCard2_(struct soap*, struct __tempuri__GetVipCard2_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___tempuri__GetVipCard2_(struct soap*, const struct __tempuri__GetVipCard2_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___tempuri__GetVipCard2_(struct soap*, const char*, int, const struct __tempuri__GetVipCard2_ *, const char*);
SOAP_FMAC3 struct __tempuri__GetVipCard2_ * SOAP_FMAC4 soap_in___tempuri__GetVipCard2_(struct soap*, const char*, struct __tempuri__GetVipCard2_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___tempuri__GetVipCard2_(struct soap*, const struct __tempuri__GetVipCard2_ *, const char*, const char*);

#ifndef soap_write___tempuri__GetVipCard2_
#define soap_write___tempuri__GetVipCard2_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___tempuri__GetVipCard2_(soap, data),0) || soap_put___tempuri__GetVipCard2_(soap, data, "-tempuri:GetVipCard2", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __tempuri__GetVipCard2_ * SOAP_FMAC4 soap_get___tempuri__GetVipCard2_(struct soap*, struct __tempuri__GetVipCard2_ *, const char*, const char*);

#ifndef soap_read___tempuri__GetVipCard2_
#define soap_read___tempuri__GetVipCard2_(soap, data) ( soap_begin_recv(soap) || !soap_get___tempuri__GetVipCard2_(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE___tempuri__GetVipCard_
#define SOAP_TYPE___tempuri__GetVipCard_ (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___tempuri__GetVipCard_(struct soap*, struct __tempuri__GetVipCard_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___tempuri__GetVipCard_(struct soap*, const struct __tempuri__GetVipCard_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___tempuri__GetVipCard_(struct soap*, const char*, int, const struct __tempuri__GetVipCard_ *, const char*);
SOAP_FMAC3 struct __tempuri__GetVipCard_ * SOAP_FMAC4 soap_in___tempuri__GetVipCard_(struct soap*, const char*, struct __tempuri__GetVipCard_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___tempuri__GetVipCard_(struct soap*, const struct __tempuri__GetVipCard_ *, const char*, const char*);

#ifndef soap_write___tempuri__GetVipCard_
#define soap_write___tempuri__GetVipCard_(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___tempuri__GetVipCard_(soap, data),0) || soap_put___tempuri__GetVipCard_(soap, data, "-tempuri:GetVipCard", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __tempuri__GetVipCard_ * SOAP_FMAC4 soap_get___tempuri__GetVipCard_(struct soap*, struct __tempuri__GetVipCard_ *, const char*, const char*);

#ifndef soap_read___tempuri__GetVipCard_
#define soap_read___tempuri__GetVipCard_(soap, data) ( soap_begin_recv(soap) || !soap_get___tempuri__GetVipCard_(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE___tempuri__Test
#define SOAP_TYPE___tempuri__Test (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___tempuri__Test(struct soap*, struct __tempuri__Test *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___tempuri__Test(struct soap*, const struct __tempuri__Test *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___tempuri__Test(struct soap*, const char*, int, const struct __tempuri__Test *, const char*);
SOAP_FMAC3 struct __tempuri__Test * SOAP_FMAC4 soap_in___tempuri__Test(struct soap*, const char*, struct __tempuri__Test *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___tempuri__Test(struct soap*, const struct __tempuri__Test *, const char*, const char*);

#ifndef soap_write___tempuri__Test
#define soap_write___tempuri__Test(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___tempuri__Test(soap, data),0) || soap_put___tempuri__Test(soap, data, "-tempuri:Test", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __tempuri__Test * SOAP_FMAC4 soap_get___tempuri__Test(struct soap*, struct __tempuri__Test *, const char*, const char*);

#ifndef soap_read___tempuri__Test
#define soap_read___tempuri__Test(soap, data) ( soap_begin_recv(soap) || !soap_get___tempuri__Test(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE___tempuri__GetCardBuyList
#define SOAP_TYPE___tempuri__GetCardBuyList (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___tempuri__GetCardBuyList(struct soap*, struct __tempuri__GetCardBuyList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___tempuri__GetCardBuyList(struct soap*, const struct __tempuri__GetCardBuyList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___tempuri__GetCardBuyList(struct soap*, const char*, int, const struct __tempuri__GetCardBuyList *, const char*);
SOAP_FMAC3 struct __tempuri__GetCardBuyList * SOAP_FMAC4 soap_in___tempuri__GetCardBuyList(struct soap*, const char*, struct __tempuri__GetCardBuyList *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___tempuri__GetCardBuyList(struct soap*, const struct __tempuri__GetCardBuyList *, const char*, const char*);

#ifndef soap_write___tempuri__GetCardBuyList
#define soap_write___tempuri__GetCardBuyList(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___tempuri__GetCardBuyList(soap, data),0) || soap_put___tempuri__GetCardBuyList(soap, data, "-tempuri:GetCardBuyList", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __tempuri__GetCardBuyList * SOAP_FMAC4 soap_get___tempuri__GetCardBuyList(struct soap*, struct __tempuri__GetCardBuyList *, const char*, const char*);

#ifndef soap_read___tempuri__GetCardBuyList
#define soap_read___tempuri__GetCardBuyList(soap, data) ( soap_begin_recv(soap) || !soap_get___tempuri__GetCardBuyList(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE___tempuri__UpdateMemberInfo
#define SOAP_TYPE___tempuri__UpdateMemberInfo (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___tempuri__UpdateMemberInfo(struct soap*, struct __tempuri__UpdateMemberInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___tempuri__UpdateMemberInfo(struct soap*, const struct __tempuri__UpdateMemberInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___tempuri__UpdateMemberInfo(struct soap*, const char*, int, const struct __tempuri__UpdateMemberInfo *, const char*);
SOAP_FMAC3 struct __tempuri__UpdateMemberInfo * SOAP_FMAC4 soap_in___tempuri__UpdateMemberInfo(struct soap*, const char*, struct __tempuri__UpdateMemberInfo *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___tempuri__UpdateMemberInfo(struct soap*, const struct __tempuri__UpdateMemberInfo *, const char*, const char*);

#ifndef soap_write___tempuri__UpdateMemberInfo
#define soap_write___tempuri__UpdateMemberInfo(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___tempuri__UpdateMemberInfo(soap, data),0) || soap_put___tempuri__UpdateMemberInfo(soap, data, "-tempuri:UpdateMemberInfo", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __tempuri__UpdateMemberInfo * SOAP_FMAC4 soap_get___tempuri__UpdateMemberInfo(struct soap*, struct __tempuri__UpdateMemberInfo *, const char*, const char*);

#ifndef soap_read___tempuri__UpdateMemberInfo
#define soap_read___tempuri__UpdateMemberInfo(soap, data) ( soap_begin_recv(soap) || !soap_get___tempuri__UpdateMemberInfo(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE___tempuri__VipRegisterInfo
#define SOAP_TYPE___tempuri__VipRegisterInfo (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___tempuri__VipRegisterInfo(struct soap*, struct __tempuri__VipRegisterInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___tempuri__VipRegisterInfo(struct soap*, const struct __tempuri__VipRegisterInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___tempuri__VipRegisterInfo(struct soap*, const char*, int, const struct __tempuri__VipRegisterInfo *, const char*);
SOAP_FMAC3 struct __tempuri__VipRegisterInfo * SOAP_FMAC4 soap_in___tempuri__VipRegisterInfo(struct soap*, const char*, struct __tempuri__VipRegisterInfo *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___tempuri__VipRegisterInfo(struct soap*, const struct __tempuri__VipRegisterInfo *, const char*, const char*);

#ifndef soap_write___tempuri__VipRegisterInfo
#define soap_write___tempuri__VipRegisterInfo(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___tempuri__VipRegisterInfo(soap, data),0) || soap_put___tempuri__VipRegisterInfo(soap, data, "-tempuri:VipRegisterInfo", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __tempuri__VipRegisterInfo * SOAP_FMAC4 soap_get___tempuri__VipRegisterInfo(struct soap*, struct __tempuri__VipRegisterInfo *, const char*, const char*);

#ifndef soap_read___tempuri__VipRegisterInfo
#define soap_read___tempuri__VipRegisterInfo(soap, data) ( soap_begin_recv(soap) || !soap_get___tempuri__VipRegisterInfo(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE___tempuri__UpdateVipCent
#define SOAP_TYPE___tempuri__UpdateVipCent (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___tempuri__UpdateVipCent(struct soap*, struct __tempuri__UpdateVipCent *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___tempuri__UpdateVipCent(struct soap*, const struct __tempuri__UpdateVipCent *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___tempuri__UpdateVipCent(struct soap*, const char*, int, const struct __tempuri__UpdateVipCent *, const char*);
SOAP_FMAC3 struct __tempuri__UpdateVipCent * SOAP_FMAC4 soap_in___tempuri__UpdateVipCent(struct soap*, const char*, struct __tempuri__UpdateVipCent *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___tempuri__UpdateVipCent(struct soap*, const struct __tempuri__UpdateVipCent *, const char*, const char*);

#ifndef soap_write___tempuri__UpdateVipCent
#define soap_write___tempuri__UpdateVipCent(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___tempuri__UpdateVipCent(soap, data),0) || soap_put___tempuri__UpdateVipCent(soap, data, "-tempuri:UpdateVipCent", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __tempuri__UpdateVipCent * SOAP_FMAC4 soap_get___tempuri__UpdateVipCent(struct soap*, struct __tempuri__UpdateVipCent *, const char*, const char*);

#ifndef soap_read___tempuri__UpdateVipCent
#define soap_read___tempuri__UpdateVipCent(soap, data) ( soap_begin_recv(soap) || !soap_get___tempuri__UpdateVipCent(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE___tempuri__GetVipCard2
#define SOAP_TYPE___tempuri__GetVipCard2 (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___tempuri__GetVipCard2(struct soap*, struct __tempuri__GetVipCard2 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___tempuri__GetVipCard2(struct soap*, const struct __tempuri__GetVipCard2 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___tempuri__GetVipCard2(struct soap*, const char*, int, const struct __tempuri__GetVipCard2 *, const char*);
SOAP_FMAC3 struct __tempuri__GetVipCard2 * SOAP_FMAC4 soap_in___tempuri__GetVipCard2(struct soap*, const char*, struct __tempuri__GetVipCard2 *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___tempuri__GetVipCard2(struct soap*, const struct __tempuri__GetVipCard2 *, const char*, const char*);

#ifndef soap_write___tempuri__GetVipCard2
#define soap_write___tempuri__GetVipCard2(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___tempuri__GetVipCard2(soap, data),0) || soap_put___tempuri__GetVipCard2(soap, data, "-tempuri:GetVipCard2", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __tempuri__GetVipCard2 * SOAP_FMAC4 soap_get___tempuri__GetVipCard2(struct soap*, struct __tempuri__GetVipCard2 *, const char*, const char*);

#ifndef soap_read___tempuri__GetVipCard2
#define soap_read___tempuri__GetVipCard2(soap, data) ( soap_begin_recv(soap) || !soap_get___tempuri__GetVipCard2(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE___tempuri__GetVipCard
#define SOAP_TYPE___tempuri__GetVipCard (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___tempuri__GetVipCard(struct soap*, struct __tempuri__GetVipCard *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___tempuri__GetVipCard(struct soap*, const struct __tempuri__GetVipCard *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___tempuri__GetVipCard(struct soap*, const char*, int, const struct __tempuri__GetVipCard *, const char*);
SOAP_FMAC3 struct __tempuri__GetVipCard * SOAP_FMAC4 soap_in___tempuri__GetVipCard(struct soap*, const char*, struct __tempuri__GetVipCard *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___tempuri__GetVipCard(struct soap*, const struct __tempuri__GetVipCard *, const char*, const char*);

#ifndef soap_write___tempuri__GetVipCard
#define soap_write___tempuri__GetVipCard(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___tempuri__GetVipCard(soap, data),0) || soap_put___tempuri__GetVipCard(soap, data, "-tempuri:GetVipCard", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __tempuri__GetVipCard * SOAP_FMAC4 soap_get___tempuri__GetVipCard(struct soap*, struct __tempuri__GetVipCard *, const char*, const char*);

#ifndef soap_read___tempuri__GetVipCard
#define soap_read___tempuri__GetVipCard(soap, data) ( soap_begin_recv(soap) || !soap_get___tempuri__GetVipCard(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data),0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE__tempuri__TestResponse
#define SOAP_TYPE__tempuri__TestResponse (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__tempuri__TestResponse(struct soap*, struct _tempuri__TestResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__tempuri__TestResponse(struct soap*, const struct _tempuri__TestResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__tempuri__TestResponse(struct soap*, const char*, int, const struct _tempuri__TestResponse *, const char*);
SOAP_FMAC3 struct _tempuri__TestResponse * SOAP_FMAC4 soap_in__tempuri__TestResponse(struct soap*, const char*, struct _tempuri__TestResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put__tempuri__TestResponse(struct soap*, const struct _tempuri__TestResponse *, const char*, const char*);

#ifndef soap_write__tempuri__TestResponse
#define soap_write__tempuri__TestResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__tempuri__TestResponse(soap, data),0) || soap_put__tempuri__TestResponse(soap, data, "tempuri:TestResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__TestResponse * SOAP_FMAC4 soap_get__tempuri__TestResponse(struct soap*, struct _tempuri__TestResponse *, const char*, const char*);

#ifndef soap_read__tempuri__TestResponse
#define soap_read__tempuri__TestResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__tempuri__TestResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__tempuri__Test
#define SOAP_TYPE__tempuri__Test (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__tempuri__Test(struct soap*, struct _tempuri__Test *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__tempuri__Test(struct soap*, const struct _tempuri__Test *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__tempuri__Test(struct soap*, const char*, int, const struct _tempuri__Test *, const char*);
SOAP_FMAC3 struct _tempuri__Test * SOAP_FMAC4 soap_in__tempuri__Test(struct soap*, const char*, struct _tempuri__Test *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put__tempuri__Test(struct soap*, const struct _tempuri__Test *, const char*, const char*);

#ifndef soap_write__tempuri__Test
#define soap_write__tempuri__Test(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__tempuri__Test(soap, data),0) || soap_put__tempuri__Test(soap, data, "tempuri:Test", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__Test * SOAP_FMAC4 soap_get__tempuri__Test(struct soap*, struct _tempuri__Test *, const char*, const char*);

#ifndef soap_read__tempuri__Test
#define soap_read__tempuri__Test(soap, data) ( soap_begin_recv(soap) || !soap_get__tempuri__Test(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__tempuri__GetCardBuyListResponse
#define SOAP_TYPE__tempuri__GetCardBuyListResponse (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__tempuri__GetCardBuyListResponse(struct soap*, struct _tempuri__GetCardBuyListResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__tempuri__GetCardBuyListResponse(struct soap*, const struct _tempuri__GetCardBuyListResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__tempuri__GetCardBuyListResponse(struct soap*, const char*, int, const struct _tempuri__GetCardBuyListResponse *, const char*);
SOAP_FMAC3 struct _tempuri__GetCardBuyListResponse * SOAP_FMAC4 soap_in__tempuri__GetCardBuyListResponse(struct soap*, const char*, struct _tempuri__GetCardBuyListResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put__tempuri__GetCardBuyListResponse(struct soap*, const struct _tempuri__GetCardBuyListResponse *, const char*, const char*);

#ifndef soap_write__tempuri__GetCardBuyListResponse
#define soap_write__tempuri__GetCardBuyListResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__tempuri__GetCardBuyListResponse(soap, data),0) || soap_put__tempuri__GetCardBuyListResponse(soap, data, "tempuri:GetCardBuyListResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__GetCardBuyListResponse * SOAP_FMAC4 soap_get__tempuri__GetCardBuyListResponse(struct soap*, struct _tempuri__GetCardBuyListResponse *, const char*, const char*);

#ifndef soap_read__tempuri__GetCardBuyListResponse
#define soap_read__tempuri__GetCardBuyListResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__tempuri__GetCardBuyListResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__tempuri__GetCardBuyList
#define SOAP_TYPE__tempuri__GetCardBuyList (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__tempuri__GetCardBuyList(struct soap*, struct _tempuri__GetCardBuyList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__tempuri__GetCardBuyList(struct soap*, const struct _tempuri__GetCardBuyList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__tempuri__GetCardBuyList(struct soap*, const char*, int, const struct _tempuri__GetCardBuyList *, const char*);
SOAP_FMAC3 struct _tempuri__GetCardBuyList * SOAP_FMAC4 soap_in__tempuri__GetCardBuyList(struct soap*, const char*, struct _tempuri__GetCardBuyList *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put__tempuri__GetCardBuyList(struct soap*, const struct _tempuri__GetCardBuyList *, const char*, const char*);

#ifndef soap_write__tempuri__GetCardBuyList
#define soap_write__tempuri__GetCardBuyList(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__tempuri__GetCardBuyList(soap, data),0) || soap_put__tempuri__GetCardBuyList(soap, data, "tempuri:GetCardBuyList", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__GetCardBuyList * SOAP_FMAC4 soap_get__tempuri__GetCardBuyList(struct soap*, struct _tempuri__GetCardBuyList *, const char*, const char*);

#ifndef soap_read__tempuri__GetCardBuyList
#define soap_read__tempuri__GetCardBuyList(soap, data) ( soap_begin_recv(soap) || !soap_get__tempuri__GetCardBuyList(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__tempuri__UpdateMemberInfoResponse
#define SOAP_TYPE__tempuri__UpdateMemberInfoResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__tempuri__UpdateMemberInfoResponse(struct soap*, struct _tempuri__UpdateMemberInfoResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__tempuri__UpdateMemberInfoResponse(struct soap*, const struct _tempuri__UpdateMemberInfoResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__tempuri__UpdateMemberInfoResponse(struct soap*, const char*, int, const struct _tempuri__UpdateMemberInfoResponse *, const char*);
SOAP_FMAC3 struct _tempuri__UpdateMemberInfoResponse * SOAP_FMAC4 soap_in__tempuri__UpdateMemberInfoResponse(struct soap*, const char*, struct _tempuri__UpdateMemberInfoResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put__tempuri__UpdateMemberInfoResponse(struct soap*, const struct _tempuri__UpdateMemberInfoResponse *, const char*, const char*);

#ifndef soap_write__tempuri__UpdateMemberInfoResponse
#define soap_write__tempuri__UpdateMemberInfoResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__tempuri__UpdateMemberInfoResponse(soap, data),0) || soap_put__tempuri__UpdateMemberInfoResponse(soap, data, "tempuri:UpdateMemberInfoResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__UpdateMemberInfoResponse * SOAP_FMAC4 soap_get__tempuri__UpdateMemberInfoResponse(struct soap*, struct _tempuri__UpdateMemberInfoResponse *, const char*, const char*);

#ifndef soap_read__tempuri__UpdateMemberInfoResponse
#define soap_read__tempuri__UpdateMemberInfoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__tempuri__UpdateMemberInfoResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__tempuri__UpdateMemberInfo
#define SOAP_TYPE__tempuri__UpdateMemberInfo (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__tempuri__UpdateMemberInfo(struct soap*, struct _tempuri__UpdateMemberInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__tempuri__UpdateMemberInfo(struct soap*, const struct _tempuri__UpdateMemberInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__tempuri__UpdateMemberInfo(struct soap*, const char*, int, const struct _tempuri__UpdateMemberInfo *, const char*);
SOAP_FMAC3 struct _tempuri__UpdateMemberInfo * SOAP_FMAC4 soap_in__tempuri__UpdateMemberInfo(struct soap*, const char*, struct _tempuri__UpdateMemberInfo *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put__tempuri__UpdateMemberInfo(struct soap*, const struct _tempuri__UpdateMemberInfo *, const char*, const char*);

#ifndef soap_write__tempuri__UpdateMemberInfo
#define soap_write__tempuri__UpdateMemberInfo(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__tempuri__UpdateMemberInfo(soap, data),0) || soap_put__tempuri__UpdateMemberInfo(soap, data, "tempuri:UpdateMemberInfo", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__UpdateMemberInfo * SOAP_FMAC4 soap_get__tempuri__UpdateMemberInfo(struct soap*, struct _tempuri__UpdateMemberInfo *, const char*, const char*);

#ifndef soap_read__tempuri__UpdateMemberInfo
#define soap_read__tempuri__UpdateMemberInfo(soap, data) ( soap_begin_recv(soap) || !soap_get__tempuri__UpdateMemberInfo(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__tempuri__VipRegisterInfoResponse
#define SOAP_TYPE__tempuri__VipRegisterInfoResponse (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__tempuri__VipRegisterInfoResponse(struct soap*, struct _tempuri__VipRegisterInfoResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__tempuri__VipRegisterInfoResponse(struct soap*, const struct _tempuri__VipRegisterInfoResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__tempuri__VipRegisterInfoResponse(struct soap*, const char*, int, const struct _tempuri__VipRegisterInfoResponse *, const char*);
SOAP_FMAC3 struct _tempuri__VipRegisterInfoResponse * SOAP_FMAC4 soap_in__tempuri__VipRegisterInfoResponse(struct soap*, const char*, struct _tempuri__VipRegisterInfoResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put__tempuri__VipRegisterInfoResponse(struct soap*, const struct _tempuri__VipRegisterInfoResponse *, const char*, const char*);

#ifndef soap_write__tempuri__VipRegisterInfoResponse
#define soap_write__tempuri__VipRegisterInfoResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__tempuri__VipRegisterInfoResponse(soap, data),0) || soap_put__tempuri__VipRegisterInfoResponse(soap, data, "tempuri:VipRegisterInfoResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__VipRegisterInfoResponse * SOAP_FMAC4 soap_get__tempuri__VipRegisterInfoResponse(struct soap*, struct _tempuri__VipRegisterInfoResponse *, const char*, const char*);

#ifndef soap_read__tempuri__VipRegisterInfoResponse
#define soap_read__tempuri__VipRegisterInfoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__tempuri__VipRegisterInfoResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__tempuri__VipRegisterInfo
#define SOAP_TYPE__tempuri__VipRegisterInfo (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__tempuri__VipRegisterInfo(struct soap*, struct _tempuri__VipRegisterInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__tempuri__VipRegisterInfo(struct soap*, const struct _tempuri__VipRegisterInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__tempuri__VipRegisterInfo(struct soap*, const char*, int, const struct _tempuri__VipRegisterInfo *, const char*);
SOAP_FMAC3 struct _tempuri__VipRegisterInfo * SOAP_FMAC4 soap_in__tempuri__VipRegisterInfo(struct soap*, const char*, struct _tempuri__VipRegisterInfo *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put__tempuri__VipRegisterInfo(struct soap*, const struct _tempuri__VipRegisterInfo *, const char*, const char*);

#ifndef soap_write__tempuri__VipRegisterInfo
#define soap_write__tempuri__VipRegisterInfo(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__tempuri__VipRegisterInfo(soap, data),0) || soap_put__tempuri__VipRegisterInfo(soap, data, "tempuri:VipRegisterInfo", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__VipRegisterInfo * SOAP_FMAC4 soap_get__tempuri__VipRegisterInfo(struct soap*, struct _tempuri__VipRegisterInfo *, const char*, const char*);

#ifndef soap_read__tempuri__VipRegisterInfo
#define soap_read__tempuri__VipRegisterInfo(soap, data) ( soap_begin_recv(soap) || !soap_get__tempuri__VipRegisterInfo(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__tempuri__UpdateVipCentResponse
#define SOAP_TYPE__tempuri__UpdateVipCentResponse (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__tempuri__UpdateVipCentResponse(struct soap*, struct _tempuri__UpdateVipCentResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__tempuri__UpdateVipCentResponse(struct soap*, const struct _tempuri__UpdateVipCentResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__tempuri__UpdateVipCentResponse(struct soap*, const char*, int, const struct _tempuri__UpdateVipCentResponse *, const char*);
SOAP_FMAC3 struct _tempuri__UpdateVipCentResponse * SOAP_FMAC4 soap_in__tempuri__UpdateVipCentResponse(struct soap*, const char*, struct _tempuri__UpdateVipCentResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put__tempuri__UpdateVipCentResponse(struct soap*, const struct _tempuri__UpdateVipCentResponse *, const char*, const char*);

#ifndef soap_write__tempuri__UpdateVipCentResponse
#define soap_write__tempuri__UpdateVipCentResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__tempuri__UpdateVipCentResponse(soap, data),0) || soap_put__tempuri__UpdateVipCentResponse(soap, data, "tempuri:UpdateVipCentResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__UpdateVipCentResponse * SOAP_FMAC4 soap_get__tempuri__UpdateVipCentResponse(struct soap*, struct _tempuri__UpdateVipCentResponse *, const char*, const char*);

#ifndef soap_read__tempuri__UpdateVipCentResponse
#define soap_read__tempuri__UpdateVipCentResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__tempuri__UpdateVipCentResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__tempuri__UpdateVipCent
#define SOAP_TYPE__tempuri__UpdateVipCent (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__tempuri__UpdateVipCent(struct soap*, struct _tempuri__UpdateVipCent *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__tempuri__UpdateVipCent(struct soap*, const struct _tempuri__UpdateVipCent *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__tempuri__UpdateVipCent(struct soap*, const char*, int, const struct _tempuri__UpdateVipCent *, const char*);
SOAP_FMAC3 struct _tempuri__UpdateVipCent * SOAP_FMAC4 soap_in__tempuri__UpdateVipCent(struct soap*, const char*, struct _tempuri__UpdateVipCent *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put__tempuri__UpdateVipCent(struct soap*, const struct _tempuri__UpdateVipCent *, const char*, const char*);

#ifndef soap_write__tempuri__UpdateVipCent
#define soap_write__tempuri__UpdateVipCent(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__tempuri__UpdateVipCent(soap, data),0) || soap_put__tempuri__UpdateVipCent(soap, data, "tempuri:UpdateVipCent", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__UpdateVipCent * SOAP_FMAC4 soap_get__tempuri__UpdateVipCent(struct soap*, struct _tempuri__UpdateVipCent *, const char*, const char*);

#ifndef soap_read__tempuri__UpdateVipCent
#define soap_read__tempuri__UpdateVipCent(soap, data) ( soap_begin_recv(soap) || !soap_get__tempuri__UpdateVipCent(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__tempuri__GetVipCard2Response
#define SOAP_TYPE__tempuri__GetVipCard2Response (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__tempuri__GetVipCard2Response(struct soap*, struct _tempuri__GetVipCard2Response *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__tempuri__GetVipCard2Response(struct soap*, const struct _tempuri__GetVipCard2Response *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__tempuri__GetVipCard2Response(struct soap*, const char*, int, const struct _tempuri__GetVipCard2Response *, const char*);
SOAP_FMAC3 struct _tempuri__GetVipCard2Response * SOAP_FMAC4 soap_in__tempuri__GetVipCard2Response(struct soap*, const char*, struct _tempuri__GetVipCard2Response *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put__tempuri__GetVipCard2Response(struct soap*, const struct _tempuri__GetVipCard2Response *, const char*, const char*);

#ifndef soap_write__tempuri__GetVipCard2Response
#define soap_write__tempuri__GetVipCard2Response(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__tempuri__GetVipCard2Response(soap, data),0) || soap_put__tempuri__GetVipCard2Response(soap, data, "tempuri:GetVipCard2Response", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__GetVipCard2Response * SOAP_FMAC4 soap_get__tempuri__GetVipCard2Response(struct soap*, struct _tempuri__GetVipCard2Response *, const char*, const char*);

#ifndef soap_read__tempuri__GetVipCard2Response
#define soap_read__tempuri__GetVipCard2Response(soap, data) ( soap_begin_recv(soap) || !soap_get__tempuri__GetVipCard2Response(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__tempuri__GetVipCard2
#define SOAP_TYPE__tempuri__GetVipCard2 (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__tempuri__GetVipCard2(struct soap*, struct _tempuri__GetVipCard2 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__tempuri__GetVipCard2(struct soap*, const struct _tempuri__GetVipCard2 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__tempuri__GetVipCard2(struct soap*, const char*, int, const struct _tempuri__GetVipCard2 *, const char*);
SOAP_FMAC3 struct _tempuri__GetVipCard2 * SOAP_FMAC4 soap_in__tempuri__GetVipCard2(struct soap*, const char*, struct _tempuri__GetVipCard2 *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put__tempuri__GetVipCard2(struct soap*, const struct _tempuri__GetVipCard2 *, const char*, const char*);

#ifndef soap_write__tempuri__GetVipCard2
#define soap_write__tempuri__GetVipCard2(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__tempuri__GetVipCard2(soap, data),0) || soap_put__tempuri__GetVipCard2(soap, data, "tempuri:GetVipCard2", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__GetVipCard2 * SOAP_FMAC4 soap_get__tempuri__GetVipCard2(struct soap*, struct _tempuri__GetVipCard2 *, const char*, const char*);

#ifndef soap_read__tempuri__GetVipCard2
#define soap_read__tempuri__GetVipCard2(soap, data) ( soap_begin_recv(soap) || !soap_get__tempuri__GetVipCard2(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__tempuri__GetVipCardResponse
#define SOAP_TYPE__tempuri__GetVipCardResponse (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__tempuri__GetVipCardResponse(struct soap*, struct _tempuri__GetVipCardResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__tempuri__GetVipCardResponse(struct soap*, const struct _tempuri__GetVipCardResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__tempuri__GetVipCardResponse(struct soap*, const char*, int, const struct _tempuri__GetVipCardResponse *, const char*);
SOAP_FMAC3 struct _tempuri__GetVipCardResponse * SOAP_FMAC4 soap_in__tempuri__GetVipCardResponse(struct soap*, const char*, struct _tempuri__GetVipCardResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put__tempuri__GetVipCardResponse(struct soap*, const struct _tempuri__GetVipCardResponse *, const char*, const char*);

#ifndef soap_write__tempuri__GetVipCardResponse
#define soap_write__tempuri__GetVipCardResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__tempuri__GetVipCardResponse(soap, data),0) || soap_put__tempuri__GetVipCardResponse(soap, data, "tempuri:GetVipCardResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__GetVipCardResponse * SOAP_FMAC4 soap_get__tempuri__GetVipCardResponse(struct soap*, struct _tempuri__GetVipCardResponse *, const char*, const char*);

#ifndef soap_read__tempuri__GetVipCardResponse
#define soap_read__tempuri__GetVipCardResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__tempuri__GetVipCardResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__tempuri__GetVipCard
#define SOAP_TYPE__tempuri__GetVipCard (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__tempuri__GetVipCard(struct soap*, struct _tempuri__GetVipCard *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__tempuri__GetVipCard(struct soap*, const struct _tempuri__GetVipCard *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__tempuri__GetVipCard(struct soap*, const char*, int, const struct _tempuri__GetVipCard *, const char*);
SOAP_FMAC3 struct _tempuri__GetVipCard * SOAP_FMAC4 soap_in__tempuri__GetVipCard(struct soap*, const char*, struct _tempuri__GetVipCard *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put__tempuri__GetVipCard(struct soap*, const struct _tempuri__GetVipCard *, const char*, const char*);

#ifndef soap_write__tempuri__GetVipCard
#define soap_write__tempuri__GetVipCard(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__tempuri__GetVipCard(soap, data),0) || soap_put__tempuri__GetVipCard(soap, data, "tempuri:GetVipCard", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__GetVipCard * SOAP_FMAC4 soap_get__tempuri__GetVipCard(struct soap*, struct _tempuri__GetVipCard *, const char*, const char*);

#ifndef soap_read__tempuri__GetVipCard
#define soap_read__tempuri__GetVipCard(soap, data) ( soap_begin_recv(soap) || !soap_get__tempuri__GetVipCard(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_tempuri__BuyData
#define SOAP_TYPE_tempuri__BuyData (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tempuri__BuyData(struct soap*, struct tempuri__BuyData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tempuri__BuyData(struct soap*, const struct tempuri__BuyData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tempuri__BuyData(struct soap*, const char*, int, const struct tempuri__BuyData *, const char*);
SOAP_FMAC3 struct tempuri__BuyData * SOAP_FMAC4 soap_in_tempuri__BuyData(struct soap*, const char*, struct tempuri__BuyData *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_tempuri__BuyData(struct soap*, const struct tempuri__BuyData *, const char*, const char*);

#ifndef soap_write_tempuri__BuyData
#define soap_write_tempuri__BuyData(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_tempuri__BuyData(soap, data),0) || soap_put_tempuri__BuyData(soap, data, "tempuri:BuyData", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct tempuri__BuyData * SOAP_FMAC4 soap_get_tempuri__BuyData(struct soap*, struct tempuri__BuyData *, const char*, const char*);

#ifndef soap_read_tempuri__BuyData
#define soap_read_tempuri__BuyData(soap, data) ( soap_begin_recv(soap) || !soap_get_tempuri__BuyData(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_tempuri__ArrayOfBuyData
#define SOAP_TYPE_tempuri__ArrayOfBuyData (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tempuri__ArrayOfBuyData(struct soap*, struct tempuri__ArrayOfBuyData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tempuri__ArrayOfBuyData(struct soap*, const struct tempuri__ArrayOfBuyData *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tempuri__ArrayOfBuyData(struct soap*, const char*, int, const struct tempuri__ArrayOfBuyData *, const char*);
SOAP_FMAC3 struct tempuri__ArrayOfBuyData * SOAP_FMAC4 soap_in_tempuri__ArrayOfBuyData(struct soap*, const char*, struct tempuri__ArrayOfBuyData *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_tempuri__ArrayOfBuyData(struct soap*, const struct tempuri__ArrayOfBuyData *, const char*, const char*);

#ifndef soap_write_tempuri__ArrayOfBuyData
#define soap_write_tempuri__ArrayOfBuyData(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_tempuri__ArrayOfBuyData(soap, data),0) || soap_put_tempuri__ArrayOfBuyData(soap, data, "tempuri:ArrayOfBuyData", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct tempuri__ArrayOfBuyData * SOAP_FMAC4 soap_get_tempuri__ArrayOfBuyData(struct soap*, struct tempuri__ArrayOfBuyData *, const char*, const char*);

#ifndef soap_read_tempuri__ArrayOfBuyData
#define soap_read_tempuri__ArrayOfBuyData(soap, data) ( soap_begin_recv(soap) || !soap_get_tempuri__ArrayOfBuyData(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_tempuri__CrmSoapHeader
#define SOAP_TYPE_tempuri__CrmSoapHeader (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tempuri__CrmSoapHeader(struct soap*, struct tempuri__CrmSoapHeader *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tempuri__CrmSoapHeader(struct soap*, const struct tempuri__CrmSoapHeader *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tempuri__CrmSoapHeader(struct soap*, const char*, int, const struct tempuri__CrmSoapHeader *, const char*);
SOAP_FMAC3 struct tempuri__CrmSoapHeader * SOAP_FMAC4 soap_in_tempuri__CrmSoapHeader(struct soap*, const char*, struct tempuri__CrmSoapHeader *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_tempuri__CrmSoapHeader(struct soap*, const struct tempuri__CrmSoapHeader *, const char*, const char*);

#ifndef soap_write_tempuri__CrmSoapHeader
#define soap_write_tempuri__CrmSoapHeader(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_tempuri__CrmSoapHeader(soap, data),0) || soap_put_tempuri__CrmSoapHeader(soap, data, "tempuri:CrmSoapHeader", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct tempuri__CrmSoapHeader * SOAP_FMAC4 soap_get_tempuri__CrmSoapHeader(struct soap*, struct tempuri__CrmSoapHeader *, const char*, const char*);

#ifndef soap_read_tempuri__CrmSoapHeader
#define soap_read_tempuri__CrmSoapHeader(soap, data) ( soap_begin_recv(soap) || !soap_get_tempuri__CrmSoapHeader(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_tempuri__VipCard
#define SOAP_TYPE_tempuri__VipCard (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_tempuri__VipCard(struct soap*, struct tempuri__VipCard *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_tempuri__VipCard(struct soap*, const struct tempuri__VipCard *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_tempuri__VipCard(struct soap*, const char*, int, const struct tempuri__VipCard *, const char*);
SOAP_FMAC3 struct tempuri__VipCard * SOAP_FMAC4 soap_in_tempuri__VipCard(struct soap*, const char*, struct tempuri__VipCard *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_tempuri__VipCard(struct soap*, const struct tempuri__VipCard *, const char*, const char*);

#ifndef soap_write_tempuri__VipCard
#define soap_write_tempuri__VipCard(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_tempuri__VipCard(soap, data),0) || soap_put_tempuri__VipCard(soap, data, "tempuri:VipCard", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct tempuri__VipCard * SOAP_FMAC4 soap_get_tempuri__VipCard(struct soap*, struct tempuri__VipCard *, const char*, const char*);

#ifndef soap_read_tempuri__VipCard
#define soap_read_tempuri__VipCard(soap, data) ( soap_begin_recv(soap) || !soap_get_tempuri__VipCard(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (82)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data),0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (81)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data),0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data),0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTo_tempuri__TestResponse
#define SOAP_TYPE_PointerTo_tempuri__TestResponse (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_tempuri__TestResponse(struct soap*, struct _tempuri__TestResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_tempuri__TestResponse(struct soap*, const char *, int, struct _tempuri__TestResponse *const*, const char *);
SOAP_FMAC3 struct _tempuri__TestResponse ** SOAP_FMAC4 soap_in_PointerTo_tempuri__TestResponse(struct soap*, const char*, struct _tempuri__TestResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_tempuri__TestResponse(struct soap*, struct _tempuri__TestResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_tempuri__TestResponse
#define soap_write_PointerTo_tempuri__TestResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_tempuri__TestResponse(soap, data),0) || soap_put_PointerTo_tempuri__TestResponse(soap, data, "tempuri:TestResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__TestResponse ** SOAP_FMAC4 soap_get_PointerTo_tempuri__TestResponse(struct soap*, struct _tempuri__TestResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_tempuri__TestResponse
#define soap_read_PointerTo_tempuri__TestResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_tempuri__TestResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_tempuri__Test
#define SOAP_TYPE_PointerTo_tempuri__Test (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_tempuri__Test(struct soap*, struct _tempuri__Test *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_tempuri__Test(struct soap*, const char *, int, struct _tempuri__Test *const*, const char *);
SOAP_FMAC3 struct _tempuri__Test ** SOAP_FMAC4 soap_in_PointerTo_tempuri__Test(struct soap*, const char*, struct _tempuri__Test **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_tempuri__Test(struct soap*, struct _tempuri__Test *const*, const char*, const char*);

#ifndef soap_write_PointerTo_tempuri__Test
#define soap_write_PointerTo_tempuri__Test(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_tempuri__Test(soap, data),0) || soap_put_PointerTo_tempuri__Test(soap, data, "tempuri:Test", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__Test ** SOAP_FMAC4 soap_get_PointerTo_tempuri__Test(struct soap*, struct _tempuri__Test **, const char*, const char*);

#ifndef soap_read_PointerTo_tempuri__Test
#define soap_read_PointerTo_tempuri__Test(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_tempuri__Test(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_tempuri__GetCardBuyListResponse
#define SOAP_TYPE_PointerTo_tempuri__GetCardBuyListResponse (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_tempuri__GetCardBuyListResponse(struct soap*, struct _tempuri__GetCardBuyListResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_tempuri__GetCardBuyListResponse(struct soap*, const char *, int, struct _tempuri__GetCardBuyListResponse *const*, const char *);
SOAP_FMAC3 struct _tempuri__GetCardBuyListResponse ** SOAP_FMAC4 soap_in_PointerTo_tempuri__GetCardBuyListResponse(struct soap*, const char*, struct _tempuri__GetCardBuyListResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_tempuri__GetCardBuyListResponse(struct soap*, struct _tempuri__GetCardBuyListResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_tempuri__GetCardBuyListResponse
#define soap_write_PointerTo_tempuri__GetCardBuyListResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_tempuri__GetCardBuyListResponse(soap, data),0) || soap_put_PointerTo_tempuri__GetCardBuyListResponse(soap, data, "tempuri:GetCardBuyListResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__GetCardBuyListResponse ** SOAP_FMAC4 soap_get_PointerTo_tempuri__GetCardBuyListResponse(struct soap*, struct _tempuri__GetCardBuyListResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_tempuri__GetCardBuyListResponse
#define soap_read_PointerTo_tempuri__GetCardBuyListResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_tempuri__GetCardBuyListResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_tempuri__GetCardBuyList
#define SOAP_TYPE_PointerTo_tempuri__GetCardBuyList (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_tempuri__GetCardBuyList(struct soap*, struct _tempuri__GetCardBuyList *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_tempuri__GetCardBuyList(struct soap*, const char *, int, struct _tempuri__GetCardBuyList *const*, const char *);
SOAP_FMAC3 struct _tempuri__GetCardBuyList ** SOAP_FMAC4 soap_in_PointerTo_tempuri__GetCardBuyList(struct soap*, const char*, struct _tempuri__GetCardBuyList **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_tempuri__GetCardBuyList(struct soap*, struct _tempuri__GetCardBuyList *const*, const char*, const char*);

#ifndef soap_write_PointerTo_tempuri__GetCardBuyList
#define soap_write_PointerTo_tempuri__GetCardBuyList(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_tempuri__GetCardBuyList(soap, data),0) || soap_put_PointerTo_tempuri__GetCardBuyList(soap, data, "tempuri:GetCardBuyList", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__GetCardBuyList ** SOAP_FMAC4 soap_get_PointerTo_tempuri__GetCardBuyList(struct soap*, struct _tempuri__GetCardBuyList **, const char*, const char*);

#ifndef soap_read_PointerTo_tempuri__GetCardBuyList
#define soap_read_PointerTo_tempuri__GetCardBuyList(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_tempuri__GetCardBuyList(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_tempuri__UpdateMemberInfoResponse
#define SOAP_TYPE_PointerTo_tempuri__UpdateMemberInfoResponse (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_tempuri__UpdateMemberInfoResponse(struct soap*, struct _tempuri__UpdateMemberInfoResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_tempuri__UpdateMemberInfoResponse(struct soap*, const char *, int, struct _tempuri__UpdateMemberInfoResponse *const*, const char *);
SOAP_FMAC3 struct _tempuri__UpdateMemberInfoResponse ** SOAP_FMAC4 soap_in_PointerTo_tempuri__UpdateMemberInfoResponse(struct soap*, const char*, struct _tempuri__UpdateMemberInfoResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_tempuri__UpdateMemberInfoResponse(struct soap*, struct _tempuri__UpdateMemberInfoResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_tempuri__UpdateMemberInfoResponse
#define soap_write_PointerTo_tempuri__UpdateMemberInfoResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_tempuri__UpdateMemberInfoResponse(soap, data),0) || soap_put_PointerTo_tempuri__UpdateMemberInfoResponse(soap, data, "tempuri:UpdateMemberInfoResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__UpdateMemberInfoResponse ** SOAP_FMAC4 soap_get_PointerTo_tempuri__UpdateMemberInfoResponse(struct soap*, struct _tempuri__UpdateMemberInfoResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_tempuri__UpdateMemberInfoResponse
#define soap_read_PointerTo_tempuri__UpdateMemberInfoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_tempuri__UpdateMemberInfoResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_tempuri__UpdateMemberInfo
#define SOAP_TYPE_PointerTo_tempuri__UpdateMemberInfo (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_tempuri__UpdateMemberInfo(struct soap*, struct _tempuri__UpdateMemberInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_tempuri__UpdateMemberInfo(struct soap*, const char *, int, struct _tempuri__UpdateMemberInfo *const*, const char *);
SOAP_FMAC3 struct _tempuri__UpdateMemberInfo ** SOAP_FMAC4 soap_in_PointerTo_tempuri__UpdateMemberInfo(struct soap*, const char*, struct _tempuri__UpdateMemberInfo **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_tempuri__UpdateMemberInfo(struct soap*, struct _tempuri__UpdateMemberInfo *const*, const char*, const char*);

#ifndef soap_write_PointerTo_tempuri__UpdateMemberInfo
#define soap_write_PointerTo_tempuri__UpdateMemberInfo(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_tempuri__UpdateMemberInfo(soap, data),0) || soap_put_PointerTo_tempuri__UpdateMemberInfo(soap, data, "tempuri:UpdateMemberInfo", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__UpdateMemberInfo ** SOAP_FMAC4 soap_get_PointerTo_tempuri__UpdateMemberInfo(struct soap*, struct _tempuri__UpdateMemberInfo **, const char*, const char*);

#ifndef soap_read_PointerTo_tempuri__UpdateMemberInfo
#define soap_read_PointerTo_tempuri__UpdateMemberInfo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_tempuri__UpdateMemberInfo(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_tempuri__VipRegisterInfoResponse
#define SOAP_TYPE_PointerTo_tempuri__VipRegisterInfoResponse (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_tempuri__VipRegisterInfoResponse(struct soap*, struct _tempuri__VipRegisterInfoResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_tempuri__VipRegisterInfoResponse(struct soap*, const char *, int, struct _tempuri__VipRegisterInfoResponse *const*, const char *);
SOAP_FMAC3 struct _tempuri__VipRegisterInfoResponse ** SOAP_FMAC4 soap_in_PointerTo_tempuri__VipRegisterInfoResponse(struct soap*, const char*, struct _tempuri__VipRegisterInfoResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_tempuri__VipRegisterInfoResponse(struct soap*, struct _tempuri__VipRegisterInfoResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_tempuri__VipRegisterInfoResponse
#define soap_write_PointerTo_tempuri__VipRegisterInfoResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_tempuri__VipRegisterInfoResponse(soap, data),0) || soap_put_PointerTo_tempuri__VipRegisterInfoResponse(soap, data, "tempuri:VipRegisterInfoResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__VipRegisterInfoResponse ** SOAP_FMAC4 soap_get_PointerTo_tempuri__VipRegisterInfoResponse(struct soap*, struct _tempuri__VipRegisterInfoResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_tempuri__VipRegisterInfoResponse
#define soap_read_PointerTo_tempuri__VipRegisterInfoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_tempuri__VipRegisterInfoResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_tempuri__VipRegisterInfo
#define SOAP_TYPE_PointerTo_tempuri__VipRegisterInfo (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_tempuri__VipRegisterInfo(struct soap*, struct _tempuri__VipRegisterInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_tempuri__VipRegisterInfo(struct soap*, const char *, int, struct _tempuri__VipRegisterInfo *const*, const char *);
SOAP_FMAC3 struct _tempuri__VipRegisterInfo ** SOAP_FMAC4 soap_in_PointerTo_tempuri__VipRegisterInfo(struct soap*, const char*, struct _tempuri__VipRegisterInfo **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_tempuri__VipRegisterInfo(struct soap*, struct _tempuri__VipRegisterInfo *const*, const char*, const char*);

#ifndef soap_write_PointerTo_tempuri__VipRegisterInfo
#define soap_write_PointerTo_tempuri__VipRegisterInfo(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_tempuri__VipRegisterInfo(soap, data),0) || soap_put_PointerTo_tempuri__VipRegisterInfo(soap, data, "tempuri:VipRegisterInfo", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__VipRegisterInfo ** SOAP_FMAC4 soap_get_PointerTo_tempuri__VipRegisterInfo(struct soap*, struct _tempuri__VipRegisterInfo **, const char*, const char*);

#ifndef soap_read_PointerTo_tempuri__VipRegisterInfo
#define soap_read_PointerTo_tempuri__VipRegisterInfo(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_tempuri__VipRegisterInfo(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_tempuri__UpdateVipCentResponse
#define SOAP_TYPE_PointerTo_tempuri__UpdateVipCentResponse (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_tempuri__UpdateVipCentResponse(struct soap*, struct _tempuri__UpdateVipCentResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_tempuri__UpdateVipCentResponse(struct soap*, const char *, int, struct _tempuri__UpdateVipCentResponse *const*, const char *);
SOAP_FMAC3 struct _tempuri__UpdateVipCentResponse ** SOAP_FMAC4 soap_in_PointerTo_tempuri__UpdateVipCentResponse(struct soap*, const char*, struct _tempuri__UpdateVipCentResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_tempuri__UpdateVipCentResponse(struct soap*, struct _tempuri__UpdateVipCentResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_tempuri__UpdateVipCentResponse
#define soap_write_PointerTo_tempuri__UpdateVipCentResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_tempuri__UpdateVipCentResponse(soap, data),0) || soap_put_PointerTo_tempuri__UpdateVipCentResponse(soap, data, "tempuri:UpdateVipCentResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__UpdateVipCentResponse ** SOAP_FMAC4 soap_get_PointerTo_tempuri__UpdateVipCentResponse(struct soap*, struct _tempuri__UpdateVipCentResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_tempuri__UpdateVipCentResponse
#define soap_read_PointerTo_tempuri__UpdateVipCentResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_tempuri__UpdateVipCentResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_tempuri__UpdateVipCent
#define SOAP_TYPE_PointerTo_tempuri__UpdateVipCent (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_tempuri__UpdateVipCent(struct soap*, struct _tempuri__UpdateVipCent *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_tempuri__UpdateVipCent(struct soap*, const char *, int, struct _tempuri__UpdateVipCent *const*, const char *);
SOAP_FMAC3 struct _tempuri__UpdateVipCent ** SOAP_FMAC4 soap_in_PointerTo_tempuri__UpdateVipCent(struct soap*, const char*, struct _tempuri__UpdateVipCent **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_tempuri__UpdateVipCent(struct soap*, struct _tempuri__UpdateVipCent *const*, const char*, const char*);

#ifndef soap_write_PointerTo_tempuri__UpdateVipCent
#define soap_write_PointerTo_tempuri__UpdateVipCent(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_tempuri__UpdateVipCent(soap, data),0) || soap_put_PointerTo_tempuri__UpdateVipCent(soap, data, "tempuri:UpdateVipCent", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__UpdateVipCent ** SOAP_FMAC4 soap_get_PointerTo_tempuri__UpdateVipCent(struct soap*, struct _tempuri__UpdateVipCent **, const char*, const char*);

#ifndef soap_read_PointerTo_tempuri__UpdateVipCent
#define soap_read_PointerTo_tempuri__UpdateVipCent(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_tempuri__UpdateVipCent(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_tempuri__GetVipCard2Response
#define SOAP_TYPE_PointerTo_tempuri__GetVipCard2Response (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_tempuri__GetVipCard2Response(struct soap*, struct _tempuri__GetVipCard2Response *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_tempuri__GetVipCard2Response(struct soap*, const char *, int, struct _tempuri__GetVipCard2Response *const*, const char *);
SOAP_FMAC3 struct _tempuri__GetVipCard2Response ** SOAP_FMAC4 soap_in_PointerTo_tempuri__GetVipCard2Response(struct soap*, const char*, struct _tempuri__GetVipCard2Response **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_tempuri__GetVipCard2Response(struct soap*, struct _tempuri__GetVipCard2Response *const*, const char*, const char*);

#ifndef soap_write_PointerTo_tempuri__GetVipCard2Response
#define soap_write_PointerTo_tempuri__GetVipCard2Response(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_tempuri__GetVipCard2Response(soap, data),0) || soap_put_PointerTo_tempuri__GetVipCard2Response(soap, data, "tempuri:GetVipCard2Response", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__GetVipCard2Response ** SOAP_FMAC4 soap_get_PointerTo_tempuri__GetVipCard2Response(struct soap*, struct _tempuri__GetVipCard2Response **, const char*, const char*);

#ifndef soap_read_PointerTo_tempuri__GetVipCard2Response
#define soap_read_PointerTo_tempuri__GetVipCard2Response(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_tempuri__GetVipCard2Response(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_tempuri__GetVipCard2
#define SOAP_TYPE_PointerTo_tempuri__GetVipCard2 (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_tempuri__GetVipCard2(struct soap*, struct _tempuri__GetVipCard2 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_tempuri__GetVipCard2(struct soap*, const char *, int, struct _tempuri__GetVipCard2 *const*, const char *);
SOAP_FMAC3 struct _tempuri__GetVipCard2 ** SOAP_FMAC4 soap_in_PointerTo_tempuri__GetVipCard2(struct soap*, const char*, struct _tempuri__GetVipCard2 **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_tempuri__GetVipCard2(struct soap*, struct _tempuri__GetVipCard2 *const*, const char*, const char*);

#ifndef soap_write_PointerTo_tempuri__GetVipCard2
#define soap_write_PointerTo_tempuri__GetVipCard2(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_tempuri__GetVipCard2(soap, data),0) || soap_put_PointerTo_tempuri__GetVipCard2(soap, data, "tempuri:GetVipCard2", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__GetVipCard2 ** SOAP_FMAC4 soap_get_PointerTo_tempuri__GetVipCard2(struct soap*, struct _tempuri__GetVipCard2 **, const char*, const char*);

#ifndef soap_read_PointerTo_tempuri__GetVipCard2
#define soap_read_PointerTo_tempuri__GetVipCard2(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_tempuri__GetVipCard2(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_tempuri__GetVipCardResponse
#define SOAP_TYPE_PointerTo_tempuri__GetVipCardResponse (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_tempuri__GetVipCardResponse(struct soap*, struct _tempuri__GetVipCardResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_tempuri__GetVipCardResponse(struct soap*, const char *, int, struct _tempuri__GetVipCardResponse *const*, const char *);
SOAP_FMAC3 struct _tempuri__GetVipCardResponse ** SOAP_FMAC4 soap_in_PointerTo_tempuri__GetVipCardResponse(struct soap*, const char*, struct _tempuri__GetVipCardResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_tempuri__GetVipCardResponse(struct soap*, struct _tempuri__GetVipCardResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_tempuri__GetVipCardResponse
#define soap_write_PointerTo_tempuri__GetVipCardResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_tempuri__GetVipCardResponse(soap, data),0) || soap_put_PointerTo_tempuri__GetVipCardResponse(soap, data, "tempuri:GetVipCardResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__GetVipCardResponse ** SOAP_FMAC4 soap_get_PointerTo_tempuri__GetVipCardResponse(struct soap*, struct _tempuri__GetVipCardResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_tempuri__GetVipCardResponse
#define soap_read_PointerTo_tempuri__GetVipCardResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_tempuri__GetVipCardResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_tempuri__GetVipCard
#define SOAP_TYPE_PointerTo_tempuri__GetVipCard (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_tempuri__GetVipCard(struct soap*, struct _tempuri__GetVipCard *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_tempuri__GetVipCard(struct soap*, const char *, int, struct _tempuri__GetVipCard *const*, const char *);
SOAP_FMAC3 struct _tempuri__GetVipCard ** SOAP_FMAC4 soap_in_PointerTo_tempuri__GetVipCard(struct soap*, const char*, struct _tempuri__GetVipCard **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_tempuri__GetVipCard(struct soap*, struct _tempuri__GetVipCard *const*, const char*, const char*);

#ifndef soap_write_PointerTo_tempuri__GetVipCard
#define soap_write_PointerTo_tempuri__GetVipCard(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_tempuri__GetVipCard(soap, data),0) || soap_put_PointerTo_tempuri__GetVipCard(soap, data, "tempuri:GetVipCard", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct _tempuri__GetVipCard ** SOAP_FMAC4 soap_get_PointerTo_tempuri__GetVipCard(struct soap*, struct _tempuri__GetVipCard **, const char*, const char*);

#ifndef soap_read_PointerTo_tempuri__GetVipCard
#define soap_read_PointerTo_tempuri__GetVipCard(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_tempuri__GetVipCard(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTotempuri__CrmSoapHeader
#define SOAP_TYPE_PointerTotempuri__CrmSoapHeader (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotempuri__CrmSoapHeader(struct soap*, struct tempuri__CrmSoapHeader *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotempuri__CrmSoapHeader(struct soap*, const char *, int, struct tempuri__CrmSoapHeader *const*, const char *);
SOAP_FMAC3 struct tempuri__CrmSoapHeader ** SOAP_FMAC4 soap_in_PointerTotempuri__CrmSoapHeader(struct soap*, const char*, struct tempuri__CrmSoapHeader **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotempuri__CrmSoapHeader(struct soap*, struct tempuri__CrmSoapHeader *const*, const char*, const char*);

#ifndef soap_write_PointerTotempuri__CrmSoapHeader
#define soap_write_PointerTotempuri__CrmSoapHeader(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTotempuri__CrmSoapHeader(soap, data),0) || soap_put_PointerTotempuri__CrmSoapHeader(soap, data, "tempuri:CrmSoapHeader", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct tempuri__CrmSoapHeader ** SOAP_FMAC4 soap_get_PointerTotempuri__CrmSoapHeader(struct soap*, struct tempuri__CrmSoapHeader **, const char*, const char*);

#ifndef soap_read_PointerTotempuri__CrmSoapHeader
#define soap_read_PointerTotempuri__CrmSoapHeader(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTotempuri__CrmSoapHeader(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTotempuri__ArrayOfBuyData
#define SOAP_TYPE_PointerTotempuri__ArrayOfBuyData (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotempuri__ArrayOfBuyData(struct soap*, struct tempuri__ArrayOfBuyData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotempuri__ArrayOfBuyData(struct soap*, const char *, int, struct tempuri__ArrayOfBuyData *const*, const char *);
SOAP_FMAC3 struct tempuri__ArrayOfBuyData ** SOAP_FMAC4 soap_in_PointerTotempuri__ArrayOfBuyData(struct soap*, const char*, struct tempuri__ArrayOfBuyData **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotempuri__ArrayOfBuyData(struct soap*, struct tempuri__ArrayOfBuyData *const*, const char*, const char*);

#ifndef soap_write_PointerTotempuri__ArrayOfBuyData
#define soap_write_PointerTotempuri__ArrayOfBuyData(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTotempuri__ArrayOfBuyData(soap, data),0) || soap_put_PointerTotempuri__ArrayOfBuyData(soap, data, "tempuri:ArrayOfBuyData", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct tempuri__ArrayOfBuyData ** SOAP_FMAC4 soap_get_PointerTotempuri__ArrayOfBuyData(struct soap*, struct tempuri__ArrayOfBuyData **, const char*, const char*);

#ifndef soap_read_PointerTotempuri__ArrayOfBuyData
#define soap_read_PointerTotempuri__ArrayOfBuyData(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTotempuri__ArrayOfBuyData(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTotempuri__VipCard
#define SOAP_TYPE_PointerTotempuri__VipCard (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotempuri__VipCard(struct soap*, struct tempuri__VipCard *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotempuri__VipCard(struct soap*, const char *, int, struct tempuri__VipCard *const*, const char *);
SOAP_FMAC3 struct tempuri__VipCard ** SOAP_FMAC4 soap_in_PointerTotempuri__VipCard(struct soap*, const char*, struct tempuri__VipCard **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotempuri__VipCard(struct soap*, struct tempuri__VipCard *const*, const char*, const char*);

#ifndef soap_write_PointerTotempuri__VipCard
#define soap_write_PointerTotempuri__VipCard(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTotempuri__VipCard(soap, data),0) || soap_put_PointerTotempuri__VipCard(soap, data, "tempuri:VipCard", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct tempuri__VipCard ** SOAP_FMAC4 soap_get_PointerTotempuri__VipCard(struct soap*, struct tempuri__VipCard **, const char*, const char*);

#ifndef soap_read_PointerTotempuri__VipCard
#define soap_read_PointerTotempuri__VipCard(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTotempuri__VipCard(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTotempuri__BuyData
#define SOAP_TYPE_PointerTotempuri__BuyData (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotempuri__BuyData(struct soap*, struct tempuri__BuyData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotempuri__BuyData(struct soap*, const char *, int, struct tempuri__BuyData *const*, const char *);
SOAP_FMAC3 struct tempuri__BuyData ** SOAP_FMAC4 soap_in_PointerTotempuri__BuyData(struct soap*, const char*, struct tempuri__BuyData **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotempuri__BuyData(struct soap*, struct tempuri__BuyData *const*, const char*, const char*);

#ifndef soap_write_PointerTotempuri__BuyData
#define soap_write_PointerTotempuri__BuyData(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTotempuri__BuyData(soap, data),0) || soap_put_PointerTotempuri__BuyData(soap, data, "tempuri:BuyData", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct tempuri__BuyData ** SOAP_FMAC4 soap_get_PointerTotempuri__BuyData(struct soap*, struct tempuri__BuyData **, const char*, const char*);

#ifndef soap_read_PointerTotempuri__BuyData
#define soap_read_PointerTotempuri__BuyData(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTotempuri__BuyData(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__QName(soap, data),0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_string(soap, data),0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
