/* soapStub.h
   Generated by gSOAP 2.8.19 from all.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_tempuri	"http://tempuri.org/"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20819
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (7)
/* xsd:boolean */
enum xsd__boolean { false_ = 0, true_ = 1 };
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_tempuri__VipCard
#define SOAP_TYPE_tempuri__VipCard (8)
/* tempuri:VipCard */
struct tempuri__VipCard
{
	int CardId;	/* required element of type xsd:int */
	char *CardCode;	/* optional element of type xsd:string */
	char *VipName;	/* optional element of type xsd:string */
	int CardTypeId;	/* required element of type xsd:int */
	char *CardTypeName;	/* optional element of type xsd:string */
	enum xsd__boolean CanCent;	/* required element of type xsd:boolean */
	enum xsd__boolean CanOwnCoupon;	/* required element of type xsd:boolean */
	enum xsd__boolean CanDisc;	/* required element of type xsd:boolean */
	enum xsd__boolean CanReturn;	/* required element of type xsd:boolean */
	double ValidCent;	/* required element of type xsd:double */
	double YearCent;	/* required element of type xsd:double */
	double StageCent;	/* required element of type xsd:double */
	char *Hello;	/* optional element of type xsd:string */
	char *IdCardCode;	/* optional element of type xsd:string */
	char *Birthday;	/* optional element of type xsd:string */
	char *Mobile;	/* optional element of type xsd:string */
	char *ValidDate;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_tempuri__CrmSoapHeader
#define SOAP_TYPE_tempuri__CrmSoapHeader (10)
/* tempuri:CrmSoapHeader */
struct tempuri__CrmSoapHeader
{
	char *UserId;	/* optional element of type xsd:string */
	char *Password;	/* optional element of type xsd:string */
	char *__anyAttribute;	/* optional attribute of type xsd:anyType */
};
#endif

#ifndef SOAP_TYPE_tempuri__ArrayOfBuyData
#define SOAP_TYPE_tempuri__ArrayOfBuyData (11)
/* tempuri:ArrayOfBuyData */
struct tempuri__ArrayOfBuyData
{
	int __sizeBuyData;	/* sequence of elements <BuyData> */
	struct tempuri__BuyData *BuyData;	/* optional element of type tempuri:BuyData */
};
#endif

#ifndef SOAP_TYPE_tempuri__BuyData
#define SOAP_TYPE_tempuri__BuyData (12)
/* tempuri:BuyData */
struct tempuri__BuyData
{
	char *PosId;	/* optional element of type xsd:string */
	int BillId;	/* required element of type xsd:int */
	char *BuyDateTime;	/* optional element of type xsd:string */
	char *StoreName;	/* optional element of type xsd:string */
	char *CounterName;	/* optional element of type xsd:string */
	char *ProductName;	/* optional element of type xsd:string */
	double BuyQty;	/* required element of type xsd:double */
	double Amount;	/* required element of type xsd:double */
	double DiscountAmount;	/* required element of type xsd:double */
	double Score;	/* required element of type xsd:double */
};
#endif

#ifndef SOAP_TYPE__tempuri__GetVipCard
#define SOAP_TYPE__tempuri__GetVipCard (14)
/* tempuri:GetVipCard */
struct _tempuri__GetVipCard
{
	int condType;	/* required element of type xsd:int */
	char *condValue;	/* optional element of type xsd:string */
	char *cardCodeToCheck;	/* optional element of type xsd:string */
	char *verifyCode;	/* optional element of type xsd:string */
	char *storeCode;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__tempuri__GetVipCardResponse
#define SOAP_TYPE__tempuri__GetVipCardResponse (15)
/* tempuri:GetVipCardResponse */
struct _tempuri__GetVipCardResponse
{
	enum xsd__boolean GetVipCardResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
	char *msg;	/* optional element of type xsd:string */
	struct tempuri__VipCard *vipCard;	/* optional element of type tempuri:VipCard */
};
#endif

#ifndef SOAP_TYPE__tempuri__GetVipCard2
#define SOAP_TYPE__tempuri__GetVipCard2 (17)
/* tempuri:GetVipCard2 */
struct _tempuri__GetVipCard2
{
	int condType;	/* required element of type xsd:int */
	char *condValue;	/* optional element of type xsd:string */
	char *cardCodeToCheck;	/* optional element of type xsd:string */
	char *verifyCode;	/* optional element of type xsd:string */
	char *storeCode;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__tempuri__GetVipCard2Response
#define SOAP_TYPE__tempuri__GetVipCard2Response (18)
/* tempuri:GetVipCard2Response */
struct _tempuri__GetVipCard2Response
{
	enum xsd__boolean GetVipCard2Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
	char *msg;	/* optional element of type xsd:string */
	struct tempuri__VipCard *vipCard;	/* optional element of type tempuri:VipCard */
};
#endif

#ifndef SOAP_TYPE__tempuri__UpdateVipCent
#define SOAP_TYPE__tempuri__UpdateVipCent (19)
/* tempuri:UpdateVipCent */
struct _tempuri__UpdateVipCent
{
	int vipId;	/* required element of type xsd:int */
	double updateCent;	/* required element of type xsd:double */
	int updateType;	/* required element of type xsd:int */
	char *storeCode;	/* optional element of type xsd:string */
	char *posId;	/* optional element of type xsd:string */
	int billId;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__tempuri__UpdateVipCentResponse
#define SOAP_TYPE__tempuri__UpdateVipCentResponse (20)
/* tempuri:UpdateVipCentResponse */
struct _tempuri__UpdateVipCentResponse
{
	enum xsd__boolean UpdateVipCentResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
	char *msg;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__tempuri__VipRegisterInfo
#define SOAP_TYPE__tempuri__VipRegisterInfo (21)
/* tempuri:VipRegisterInfo */
struct _tempuri__VipRegisterInfo
{
	char *Mobile;	/* optional element of type xsd:string */
	char *IdNumber;	/* optional element of type xsd:string */
	char *VipName;	/* optional element of type xsd:string */
	char *Email;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__tempuri__VipRegisterInfoResponse
#define SOAP_TYPE__tempuri__VipRegisterInfoResponse (22)
/* tempuri:VipRegisterInfoResponse */
struct _tempuri__VipRegisterInfoResponse
{
	enum xsd__boolean VipRegisterInfoResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
	char *msg;	/* optional element of type xsd:string */
	char *VipCode;	/* optional element of type xsd:string */
	int VipType;	/* required element of type xsd:int */
	char *Mobile_USCOREout;	/* optional element of type xsd:string */
	char *IdNumber_USCOREout;	/* optional element of type xsd:string */
	int VipId;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__tempuri__UpdateMemberInfo
#define SOAP_TYPE__tempuri__UpdateMemberInfo (23)
/* tempuri:UpdateMemberInfo */
struct _tempuri__UpdateMemberInfo
{
	int vipId;	/* required element of type xsd:int */
	char *Birthday;	/* optional element of type xsd:string */
	int Sex;	/* required element of type xsd:int */
	char *Adrress;	/* optional element of type xsd:string */
	char *Email;	/* optional element of type xsd:string */
	char *Mobile;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__tempuri__UpdateMemberInfoResponse
#define SOAP_TYPE__tempuri__UpdateMemberInfoResponse (24)
/* tempuri:UpdateMemberInfoResponse */
struct _tempuri__UpdateMemberInfoResponse
{
	enum xsd__boolean UpdateMemberInfoResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
	char *msg;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__tempuri__GetCardBuyList
#define SOAP_TYPE__tempuri__GetCardBuyList (25)
/* tempuri:GetCardBuyList */
struct _tempuri__GetCardBuyList
{
	int vipId;	/* required element of type xsd:int */
	char *strStartDate;	/* optional element of type xsd:string */
	char *strEndDate;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__tempuri__GetCardBuyListResponse
#define SOAP_TYPE__tempuri__GetCardBuyListResponse (26)
/* tempuri:GetCardBuyListResponse */
struct _tempuri__GetCardBuyListResponse
{
	enum xsd__boolean GetCardBuyListResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:boolean */
	char *msg;	/* optional element of type xsd:string */
	struct tempuri__ArrayOfBuyData *buydatas;	/* optional element of type tempuri:ArrayOfBuyData */
};
#endif

#ifndef SOAP_TYPE__tempuri__Test
#define SOAP_TYPE__tempuri__Test (28)
/* tempuri:Test */
struct _tempuri__Test
{
	char *Mobile;	/* optional element of type xsd:string */
	char *IdNumber;	/* optional element of type xsd:string */
	char *VipName;	/* optional element of type xsd:string */
	char *Email;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__tempuri__TestResponse
#define SOAP_TYPE__tempuri__TestResponse (29)
/* tempuri:TestResponse */
struct _tempuri__TestResponse
{
	char *TestResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (30)
/* SOAP Header: */
struct SOAP_ENV__Header
{
	struct tempuri__CrmSoapHeader *tempuri__CrmSoapHeader;	/* mustUnderstand */
};
#endif

#endif

#ifndef SOAP_TYPE___tempuri__GetVipCard
#define SOAP_TYPE___tempuri__GetVipCard (35)
/* Operation wrapper: */
struct __tempuri__GetVipCard
{
	struct _tempuri__GetVipCard *tempuri__GetVipCard;	/* optional element of type tempuri:GetVipCard */
};
#endif

#ifndef SOAP_TYPE___tempuri__GetVipCard2
#define SOAP_TYPE___tempuri__GetVipCard2 (39)
/* Operation wrapper: */
struct __tempuri__GetVipCard2
{
	struct _tempuri__GetVipCard2 *tempuri__GetVipCard2;	/* optional element of type tempuri:GetVipCard2 */
};
#endif

#ifndef SOAP_TYPE___tempuri__UpdateVipCent
#define SOAP_TYPE___tempuri__UpdateVipCent (43)
/* Operation wrapper: */
struct __tempuri__UpdateVipCent
{
	struct _tempuri__UpdateVipCent *tempuri__UpdateVipCent;	/* optional element of type tempuri:UpdateVipCent */
};
#endif

#ifndef SOAP_TYPE___tempuri__VipRegisterInfo
#define SOAP_TYPE___tempuri__VipRegisterInfo (47)
/* Operation wrapper: */
struct __tempuri__VipRegisterInfo
{
	struct _tempuri__VipRegisterInfo *tempuri__VipRegisterInfo;	/* optional element of type tempuri:VipRegisterInfo */
};
#endif

#ifndef SOAP_TYPE___tempuri__UpdateMemberInfo
#define SOAP_TYPE___tempuri__UpdateMemberInfo (51)
/* Operation wrapper: */
struct __tempuri__UpdateMemberInfo
{
	struct _tempuri__UpdateMemberInfo *tempuri__UpdateMemberInfo;	/* optional element of type tempuri:UpdateMemberInfo */
};
#endif

#ifndef SOAP_TYPE___tempuri__GetCardBuyList
#define SOAP_TYPE___tempuri__GetCardBuyList (55)
/* Operation wrapper: */
struct __tempuri__GetCardBuyList
{
	struct _tempuri__GetCardBuyList *tempuri__GetCardBuyList;	/* optional element of type tempuri:GetCardBuyList */
};
#endif

#ifndef SOAP_TYPE___tempuri__Test
#define SOAP_TYPE___tempuri__Test (59)
/* Operation wrapper: */
struct __tempuri__Test
{
	struct _tempuri__Test *tempuri__Test;	/* optional element of type tempuri:Test */
};
#endif

#ifndef SOAP_TYPE___tempuri__GetVipCard_
#define SOAP_TYPE___tempuri__GetVipCard_ (61)
/* Operation wrapper: */
struct __tempuri__GetVipCard_
{
	struct _tempuri__GetVipCard *tempuri__GetVipCard;	/* optional element of type tempuri:GetVipCard */
};
#endif

#ifndef SOAP_TYPE___tempuri__GetVipCard2_
#define SOAP_TYPE___tempuri__GetVipCard2_ (63)
/* Operation wrapper: */
struct __tempuri__GetVipCard2_
{
	struct _tempuri__GetVipCard2 *tempuri__GetVipCard2;	/* optional element of type tempuri:GetVipCard2 */
};
#endif

#ifndef SOAP_TYPE___tempuri__UpdateVipCent_
#define SOAP_TYPE___tempuri__UpdateVipCent_ (65)
/* Operation wrapper: */
struct __tempuri__UpdateVipCent_
{
	struct _tempuri__UpdateVipCent *tempuri__UpdateVipCent;	/* optional element of type tempuri:UpdateVipCent */
};
#endif

#ifndef SOAP_TYPE___tempuri__VipRegisterInfo_
#define SOAP_TYPE___tempuri__VipRegisterInfo_ (67)
/* Operation wrapper: */
struct __tempuri__VipRegisterInfo_
{
	struct _tempuri__VipRegisterInfo *tempuri__VipRegisterInfo;	/* optional element of type tempuri:VipRegisterInfo */
};
#endif

#ifndef SOAP_TYPE___tempuri__UpdateMemberInfo_
#define SOAP_TYPE___tempuri__UpdateMemberInfo_ (69)
/* Operation wrapper: */
struct __tempuri__UpdateMemberInfo_
{
	struct _tempuri__UpdateMemberInfo *tempuri__UpdateMemberInfo;	/* optional element of type tempuri:UpdateMemberInfo */
};
#endif

#ifndef SOAP_TYPE___tempuri__GetCardBuyList_
#define SOAP_TYPE___tempuri__GetCardBuyList_ (71)
/* Operation wrapper: */
struct __tempuri__GetCardBuyList_
{
	struct _tempuri__GetCardBuyList *tempuri__GetCardBuyList;	/* optional element of type tempuri:GetCardBuyList */
};
#endif

#ifndef SOAP_TYPE___tempuri__Test_
#define SOAP_TYPE___tempuri__Test_ (73)
/* Operation wrapper: */
struct __tempuri__Test_
{
	struct _tempuri__Test *tempuri__Test;	/* optional element of type tempuri:Test */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (74)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (76)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (79)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (80)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __tempuri__GetVipCard(struct soap*, struct _tempuri__GetVipCard *tempuri__GetVipCard, struct _tempuri__GetVipCardResponse *tempuri__GetVipCardResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__GetVipCard2(struct soap*, struct _tempuri__GetVipCard2 *tempuri__GetVipCard2, struct _tempuri__GetVipCard2Response *tempuri__GetVipCard2Response);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__UpdateVipCent(struct soap*, struct _tempuri__UpdateVipCent *tempuri__UpdateVipCent, struct _tempuri__UpdateVipCentResponse *tempuri__UpdateVipCentResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__VipRegisterInfo(struct soap*, struct _tempuri__VipRegisterInfo *tempuri__VipRegisterInfo, struct _tempuri__VipRegisterInfoResponse *tempuri__VipRegisterInfoResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__UpdateMemberInfo(struct soap*, struct _tempuri__UpdateMemberInfo *tempuri__UpdateMemberInfo, struct _tempuri__UpdateMemberInfoResponse *tempuri__UpdateMemberInfoResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__GetCardBuyList(struct soap*, struct _tempuri__GetCardBuyList *tempuri__GetCardBuyList, struct _tempuri__GetCardBuyListResponse *tempuri__GetCardBuyListResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__Test(struct soap*, struct _tempuri__Test *tempuri__Test, struct _tempuri__TestResponse *tempuri__TestResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__GetVipCard_(struct soap*, struct _tempuri__GetVipCard *tempuri__GetVipCard, struct _tempuri__GetVipCardResponse *tempuri__GetVipCardResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__GetVipCard2_(struct soap*, struct _tempuri__GetVipCard2 *tempuri__GetVipCard2, struct _tempuri__GetVipCard2Response *tempuri__GetVipCard2Response);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__UpdateVipCent_(struct soap*, struct _tempuri__UpdateVipCent *tempuri__UpdateVipCent, struct _tempuri__UpdateVipCentResponse *tempuri__UpdateVipCentResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__VipRegisterInfo_(struct soap*, struct _tempuri__VipRegisterInfo *tempuri__VipRegisterInfo, struct _tempuri__VipRegisterInfoResponse *tempuri__VipRegisterInfoResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__UpdateMemberInfo_(struct soap*, struct _tempuri__UpdateMemberInfo *tempuri__UpdateMemberInfo, struct _tempuri__UpdateMemberInfoResponse *tempuri__UpdateMemberInfoResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__GetCardBuyList_(struct soap*, struct _tempuri__GetCardBuyList *tempuri__GetCardBuyList, struct _tempuri__GetCardBuyListResponse *tempuri__GetCardBuyListResponse);

SOAP_FMAC5 int SOAP_FMAC6 __tempuri__Test_(struct soap*, struct _tempuri__Test *tempuri__Test, struct _tempuri__TestResponse *tempuri__TestResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__GetVipCard(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__GetVipCard2(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__UpdateVipCent(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__VipRegisterInfo(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__UpdateMemberInfo(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__GetCardBuyList(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Test(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__GetVipCard_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__GetVipCard2_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__UpdateVipCent_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__VipRegisterInfo_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__UpdateMemberInfo_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__GetCardBuyList_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___tempuri__Test_(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__GetVipCard(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__GetVipCard *tempuri__GetVipCard, struct _tempuri__GetVipCardResponse *tempuri__GetVipCardResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__GetVipCard2(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__GetVipCard2 *tempuri__GetVipCard2, struct _tempuri__GetVipCard2Response *tempuri__GetVipCard2Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__UpdateVipCent(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__UpdateVipCent *tempuri__UpdateVipCent, struct _tempuri__UpdateVipCentResponse *tempuri__UpdateVipCentResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__VipRegisterInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__VipRegisterInfo *tempuri__VipRegisterInfo, struct _tempuri__VipRegisterInfoResponse *tempuri__VipRegisterInfoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__UpdateMemberInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__UpdateMemberInfo *tempuri__UpdateMemberInfo, struct _tempuri__UpdateMemberInfoResponse *tempuri__UpdateMemberInfoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__GetCardBuyList(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__GetCardBuyList *tempuri__GetCardBuyList, struct _tempuri__GetCardBuyListResponse *tempuri__GetCardBuyListResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__Test(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__Test *tempuri__Test, struct _tempuri__TestResponse *tempuri__TestResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__GetVipCard_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__GetVipCard *tempuri__GetVipCard, struct _tempuri__GetVipCardResponse *tempuri__GetVipCardResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__GetVipCard2_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__GetVipCard2 *tempuri__GetVipCard2, struct _tempuri__GetVipCard2Response *tempuri__GetVipCard2Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__UpdateVipCent_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__UpdateVipCent *tempuri__UpdateVipCent, struct _tempuri__UpdateVipCentResponse *tempuri__UpdateVipCentResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__VipRegisterInfo_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__VipRegisterInfo *tempuri__VipRegisterInfo, struct _tempuri__VipRegisterInfoResponse *tempuri__VipRegisterInfoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__UpdateMemberInfo_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__UpdateMemberInfo *tempuri__UpdateMemberInfo, struct _tempuri__UpdateMemberInfoResponse *tempuri__UpdateMemberInfoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__GetCardBuyList_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__GetCardBuyList *tempuri__GetCardBuyList, struct _tempuri__GetCardBuyListResponse *tempuri__GetCardBuyListResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___tempuri__Test_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _tempuri__Test *tempuri__Test, struct _tempuri__TestResponse *tempuri__TestResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
